/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import data.Persistencia;
import domain.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.InvalidPropertiesFormatException;
import javax.swing.JOptionPane;

/**
 *
 * @author ruilope
 */
public class AgregarAnimalesView extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAnimalesView
     */
    public AgregarAnimalesView() {
        initComponents();
        cargarCb();
        habilitarValorfijo();
        anadirListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cargarCb() {
        ArrayList<Especie> especies = Controlador.getEspecies();

        for (Especie especie : especies) {
            CbEspecie.addItem(especie.getNombre());
        }

        ArrayList<Sector> sectores = Controlador.getSectores();

        for (Sector sector : sectores) {
            CbSector.addItem(String.valueOf(sector.getNumero()));
        }
        ArrayList<Pais> paises = Controlador.getPaises();
        for (Pais pais : paises) {
            CbPaisOrigen.addItem(pais.getNombre());
        }

        for (TipoAlimentacion tipo : Controlador.getTiposAlimentacion()) {
            CbTipoAlimentacion.addItem(tipo);
        }

    }

    public void anadirListeners() {

        BtnVolver.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Cierra la ventana actual
                MenuView view = new MenuView();
                view.setLocationRelativeTo(null);
                view.setVisible(true);
            }
        });

        CbTipoAlimentacion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                habilitarValorfijo();
            }
        });

        BtnGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (CbTipoAlimentacion.getSelectedItem() == TipoAlimentacion.HERBIVORO) {

                    try {
                        Controlador.guardarAnimal(new Herbivoro(
                                getEdad(), getPeso(), getEspecie(), getSector(), getValorFijo(), getPais()
                        ));

                    } catch (InvalidPropertiesFormatException ev) {
                        // Manejo del error (mostrar mensaje, log, etc.)
                        ev.printStackTrace();

                    }

                } else if (CbTipoAlimentacion.getSelectedItem() == TipoAlimentacion.CARNIVORO) {

                    try {
                        Controlador.guardarAnimal(new Carnivoro(
                                getEdad(), getPeso(), getEspecie(), getSector(), getPais()
                        ));

                    } catch (InvalidPropertiesFormatException ev) {
                        // Manejo del error (mostrar mensaje, log, etc.)
                        ev.printStackTrace();

                    }

                }
            }
        });
    }

    public Especie getEspecie() {
        String nombreEspecie = String.valueOf(CbEspecie.getSelectedItem());
        for (Especie especie : Controlador.getEspecies()) {
            if (nombreEspecie.equals(especie.getNombre())) {
                return especie;
            }
        }
        return null;
    }

    public Pais getPais() {
        String nombrePais = String.valueOf(CbPaisOrigen.getSelectedItem());
        for (Pais pais : Controlador.getPaises()) {
            if (nombrePais.equals(pais.getNombre())) {
                return pais;
            }
        }
        return null;
    }

    public Sector getSector() {
        int numeroSector = Integer.parseInt(CbSector.getSelectedItem().toString());

        for (Sector sector : Controlador.getSectores()) {
            if (numeroSector == sector.getNumero()) {
                return sector;
            }
        }
        return null;
    }

    public TipoAlimentacion getAlimentacion() {
        return (TipoAlimentacion) CbTipoAlimentacion.getSelectedItem();
    }

    public double getValorFijo() {
        return Double.parseDouble(TfValorFijo.getText());
    }

    public int getEdad() {
        return Integer.parseInt(TfEdad.getText());
    }

    public double getPeso() {
        return Double.parseDouble(TfPeso.getText());
    }

    public void habilitarValorfijo() {
        if (CbTipoAlimentacion.getSelectedItem() == TipoAlimentacion.HERBIVORO) {
            TfValorFijo.setEnabled(true);
        } else {
            TfValorFijo.setEnabled(false);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CbEspecie = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CbSector = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CbPaisOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CbTipoAlimentacion = new javax.swing.JComboBox<>();
        TfValorFijo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TfEdad = new javax.swing.JTextField();
        TfPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Especie");

        CbEspecie.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbEspecieActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Sector");

        CbSector.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Pais Origen");

        CbPaisOrigen.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Alimentacion");

        CbTipoAlimentacion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbTipoAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTipoAlimentacionActionPerformed(evt);
            }
        });

        TfValorFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfValorFijoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Valor fijo");

        TfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEdadActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Edad");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Peso");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Año/s");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("kg");

        BtnGuardar.setText("Guardar");

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setText("Ingreso de Animal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TfEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfValorFijo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbTipoAlimentacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbPaisOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbSector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(135, 135, 135))))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CbSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CbPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(CbTipoAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfValorFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnVolver))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfValorFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfValorFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfValorFijoActionPerformed

    private void CbEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbEspecieActionPerformed

    private void TfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEdadActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void CbTipoAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTipoAlimentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbTipoAlimentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAnimalesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> CbEspecie;
    private javax.swing.JComboBox<String> CbPaisOrigen;
    private javax.swing.JComboBox<String> CbSector;
    private javax.swing.JComboBox<TipoAlimentacion> CbTipoAlimentacion;
    private javax.swing.JTextField TfEdad;
    private javax.swing.JTextField TfPeso;
    private javax.swing.JTextField TfValorFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
